/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manager;
import Index.index;
import checkout.empInv;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import loginPage.loginPage;

/**
 *
 * @author Atharva
 */
public class managerPage extends javax.swing.JFrame {

    /**
     * Creates new form managerPage
     */
    index ind = new index();
    public managerPage() {
        this.setAlwaysOnTop(true);  //sets always on top
        this.setResizable(false);   //not resizable
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        managerMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        managerOrders = new javax.swing.JMenuItem();
        managerSales = new javax.swing.JMenuItem();
        managerLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WELCOME!!!");
        setResizable(false);
        setSize(new java.awt.Dimension(580, 580));

        managerMenu.setText("Menu");

        jMenuItem1.setText("Inventory");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        managerMenu.add(jMenuItem1);

        managerOrders.setText("Orders");
        managerOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerOrdersActionPerformed(evt);
            }
        });
        managerMenu.add(managerOrders);

        managerSales.setText("Employees");
        managerSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerSalesActionPerformed(evt);
            }
        });
        managerMenu.add(managerSales);

        managerLogout.setText("Log Out");
        managerLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerLogoutActionPerformed(evt);
            }
        });
        managerMenu.add(managerLogout);

        jMenuBar1.add(managerMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managerOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerOrdersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_managerOrdersActionPerformed

    private void managerSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerSalesActionPerformed
        //to addEmp:
        JFrame frame = new addEmp();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_managerSalesActionPerformed

    private void managerLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerLogoutActionPerformed
        //Logout:
        JFrame frame = new loginPage();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_managerLogoutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        //To empInv.class:
        JFrame frame = new mngInv();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managerPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managerPage().setVisible(true);
                //show sales page here!!
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem managerLogout;
    private javax.swing.JMenu managerMenu;
    private javax.swing.JMenuItem managerOrders;
    private javax.swing.JMenuItem managerSales;
    // End of variables declaration//GEN-END:variables
}
