package checkout;


import java.awt.FlowLayout;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.DefaultCellEditor;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.JFrame;
import javax.swing.SpringLayout;
import loginPage.SendBillTLS;
import loginPage.loginPage;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
    anurag lavduchand hai
 */

/**
 * @author [-_-]
 */
public class Checkout extends javax.swing.JFrame{
    /**
     * Creates new form Checkout
     */
    Double tCost;
    int ProCost,BasePr;
    
    public Checkout() {
        this.setAlwaysOnTop(true);  //sets always on top
        this.setResizable(false);   //not resizable
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int xsize = (int) tk.getScreenSize().getWidth();
        int ysize = (int) tk.getScreenSize().getHeight();
        this.setSize(xsize, ysize);
        tCost=0.0;
        ProCost = 0;
        BasePr = 100;
    }
    
    private boolean pidCheck(String pidString){
        for(int i=0;i<pidString.length();i++){
            Character test=pidString.charAt(i);
            if(test<48 || test>57)
                return false;
               
        }
    
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TotalCost = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkoutTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ProIDtext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SgstLabel = new javax.swing.JLabel();
        CgstLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        QuantText = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        Discount = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        checkoutMenu = new javax.swing.JMenu();
        checkoutInv = new javax.swing.JMenuItem();
        checkoutSales = new javax.swing.JMenuItem();
        checkoutLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHECKOUT");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 700));

        jLabel1.setText("SGST @ 2.5%");

        jLabel2.setText("CGST @ 2.5%");

        jLabel3.setText("Total Price");

        checkoutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Name", "Base Price", "Quantity", "Cost"
            }
        ));
        jScrollPane1.setViewportView(checkoutTable);

        jButton1.setText("Add Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove Product");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ProIDtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProIDtextActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Product ID");

        jLabel5.setText("Quantity");

        QuantText.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jButton3.setText("Apply Changes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Discount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiscountActionPerformed(evt);
            }
        });

        jButton4.setText("Apply ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText("CODE :");

        jButton5.setText("Print Bill");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        checkoutMenu.setText("Menu");

        checkoutInv.setText("Inventory");
        checkoutMenu.add(checkoutInv);

        checkoutSales.setText("Sales");
        checkoutMenu.add(checkoutSales);

        checkoutLogout.setText("Log Out");
        checkoutLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutLogoutActionPerformed(evt);
            }
        });
        checkoutMenu.add(checkoutLogout);

        jMenuBar1.add(checkoutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SgstLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CgstLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuantText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(ProIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SgstLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Discount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))))
                    .addComponent(CgstLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Remove Row:
        DefaultTableModel model = (DefaultTableModel) checkoutTable.getModel();
        int i = checkoutTable.getSelectedRow();
        tCost = tCost - ((Integer)model.getValueAt(i,4 ));
        double tax=0.025*tCost;
        SgstLabel.setText(Double.toString(tax));    
        CgstLabel.setText(Double.toString(tax));
        double fCost = tCost + 2*tax;
        TotalCost.setText(Double.toString(fCost));
        model.removeRow(checkoutTable.getSelectedRow());
    }//GEN-LAST:event_jButton2ActionPerformed
 
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int quantity;
        Boolean flag=false;
        int row=0,qty=0;
        String productID, Name="XYZ";
        productID=ProIDtext.getText();
        if(!pidCheck(productID) || productID.isEmpty())
            JOptionPane.showMessageDialog(this,"Product ID has to be an numeric and cannot be null","Error",JOptionPane.INFORMATION_MESSAGE);
        else{
                //checking if pid is already present
           DefaultTableModel m = (DefaultTableModel) checkoutTable.getModel();
           for(int i=0;i<checkoutTable.getRowCount();i++)
           {
               if(m.getValueAt(i,0).equals(productID))
               {
                   flag = true;
                   row = i;
               }
           }
            if(flag)
            {
                //If ProductID exists increase qty                
                quantity=(Integer)QuantText.getValue();
                qty = (Integer)m.getValueAt(row, 3);
                qty += quantity;
                m.setValueAt(qty, row, 3);
                ProCost=BasePr*qty;
                m.setValueAt(ProCost, row, 4);
                tCost = (double)ProCost;
                double tax=0.025*tCost;
                SgstLabel.setText(Double.toString(tax));    
                CgstLabel.setText(Double.toString(tax));
                double fCost = tCost + 2*tax;
                TotalCost.setText(Double.toString(fCost));
                QuantText.setValue(1);                
            }
            else{
                //Code for getting product values goes here
                quantity=(Integer)QuantText.getValue();
               
                ProCost=BasePr*quantity;
                //Add Row with the above obtained product details:
        
                DefaultTableModel model = (DefaultTableModel)checkoutTable.getModel();
                model.addRow(new Object[]{productID,Name,BasePr,quantity,ProCost});
                tCost = tCost+ProCost;
                double tax=0.025*tCost;
                SgstLabel.setText(Double.toString(tax));    
                CgstLabel.setText(Double.toString(tax));
                double fCost = tCost + 2*tax;
                TotalCost.setText(Double.toString(fCost));
                QuantText.setValue(1);
        }
    }
        ProIDtext.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ProIDtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProIDtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProIDtextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m = (DefaultTableModel) checkoutTable.getModel();
        int qty;
        for(int i=0;i<checkoutTable.getRowCount();i++)
        {
            if(i==checkoutTable.getSelectedRow())
                qty = Integer.parseInt((String)m.getValueAt(i, 3));
            else
                qty = (Integer)m.getValueAt(i, 3);
            if(qty<1)
                qty = 1;
            m.setValueAt(qty, i, 3);
            ProCost=BasePr*qty;
            m.setValueAt(ProCost, i, 4);
        }
        tCost = 0.0;
        for(int i=0;i<checkoutTable.getRowCount();i++)
        {
            tCost += (Integer)m.getValueAt(i, 4);
        }
        double tax=0.025*tCost;
        SgstLabel.setText(Double.toString(tax));    
        CgstLabel.setText(Double.toString(tax));
        double fCost = tCost + 2*tax;
        TotalCost.setText(Double.toString(fCost));
        QuantText.setValue(1);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void DiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiscountActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Discount:
        DefaultTableModel m = (DefaultTableModel) checkoutTable.getModel();
        double discount = 0.2;
        String code;
        code = Discount.getText().toLowerCase();
        if(code.equals("bhikari"))
        {
            tCost = 0.0;
            for(int i=0;i<checkoutTable.getRowCount();i++)
            {
                tCost += (Integer)m.getValueAt(i, 4);
            }
            tCost -= tCost*discount;
            double tax=0.025*tCost;
            SgstLabel.setText(Double.toString(tax));    
            CgstLabel.setText(Double.toString(tax));
            double fCost = tCost + 2*tax;
            TotalCost.setText(Double.toString(fCost));
            jButton4.setEnabled(false);
        }
        else
        {
            JOptionPane.showMessageDialog(this,"Invalid Coupon","Error",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void checkoutLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutLogoutActionPerformed
        //Logout:
        JFrame frame = new loginPage();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_checkoutLogoutActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //Print Bill:
        try {

            String pathToExportTo="d:/SDL/InventoryManagement/src/checkout/bill.csv";
            DefaultTableModel model = (DefaultTableModel) checkoutTable.getModel();
            FileWriter csv = new FileWriter(new File(pathToExportTo));

            for (int i = 0; i < model.getColumnCount(); i++) {
                csv.write(model.getColumnName(i) + ",");
            }
            csv.write("\n");
            for (int i = 0; i < model.getRowCount(); i++) {
                for (int j = 0; j < model.getColumnCount(); j++) {
                    csv.write(model.getValueAt(i, j).toString() + ",");
                }
                csv.write("\n");
            }
            csv.write("\n\nSgst"+","+SgstLabel.getText()+"\n");
            csv.write("Cgst"+","+CgstLabel.getText()+"\n");
            csv.write("CODE"+","+Discount.getText()+"\n");
            csv.write("Total"+","+TotalCost.getText()+"\n");
            csv.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        String id = JOptionPane.showInputDialog(this,"Enter Email ID:");
        SendBillTLS object=new SendBillTLS(id);
        object.Execute();
    }//GEN-LAST:event_jButton5ActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CgstLabel;
    private javax.swing.JTextField Discount;
    private javax.swing.JTextField ProIDtext;
    private javax.swing.JSpinner QuantText;
    private javax.swing.JLabel SgstLabel;
    private javax.swing.JTextField TotalCost;
    private javax.swing.JMenuItem checkoutInv;
    private javax.swing.JMenuItem checkoutLogout;
    private javax.swing.JMenu checkoutMenu;
    private javax.swing.JMenuItem checkoutSales;
    private javax.swing.JTable checkoutTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
};
