package checkout;


import java.awt.FlowLayout;
import java.awt.Toolkit;
import javax.swing.DefaultCellEditor;
import javax.swing.GroupLayout;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.JFrame;
import javax.swing.SpringLayout;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author [-_-]
 */
public class Checkout extends javax.swing.JFrame{
    /**
     * Creates new form Checkout
     */
    Double tCost;
    int ProCost,BasePr;
    
    public Checkout() {
        this.setAlwaysOnTop(true);  //sets always on top
        this.setResizable(false);   //not resizable
        initComponents();
//        Toolkit tk = Toolkit.getDefaultToolkit();
//        int xsize = (int) tk.getScreenSize().getWidth();
//        int ysize = (int) tk.getScreenSize().getHeight();
//        this.setSize(xsize, ysize);
        tCost=0.0;
        ProCost = 0;
        BasePr = 100;
    }
    
    private boolean pidCheck(String pidString){
        for(int i=0;i<pidString.length();i++){
            Character test=pidString.charAt(i);
            if(test<48 || test>57)
                return false;
               
        }
    
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TotalCost = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        checkoutTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ProIDtext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SgstLabel = new javax.swing.JLabel();
        CgstLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        QuantText = new javax.swing.JSpinner();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        checkoutMenu = new javax.swing.JMenu();
        checkoutInv = new javax.swing.JMenuItem();
        checkoutSales = new javax.swing.JMenuItem();
        checkoutLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CHECKOUT");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(700, 700));

        jLabel1.setText("SGST @ 2.5%");

        jLabel2.setText("CGST @ 2.5$");

        jLabel3.setText("Total Price");

        checkoutTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ProductID", "Name", "Base Price", "Quantity", "Cost"
            }
        ));
        jScrollPane1.setViewportView(checkoutTable);

        jButton1.setText("Add Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove Product");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ProIDtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProIDtextActionPerformed(evt);
            }
        });

        jLabel4.setText("Enter Product ID");

        jLabel5.setText("Quantity");

        QuantText.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jButton3.setText("Apply Changes");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        checkoutMenu.setText("Menu");

        checkoutInv.setText("Inventory");
        checkoutMenu.add(checkoutInv);

        checkoutSales.setText("Sales");
        checkoutMenu.add(checkoutSales);

        checkoutLogout.setText("Log Out");
        checkoutMenu.add(checkoutLogout);

        jMenuBar1.add(checkoutMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 664, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SgstLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CgstLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(QuantText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(ProIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProIDtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(QuantText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SgstLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2))
                    .addComponent(CgstLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Remove Row:
        DefaultTableModel model = (DefaultTableModel) checkoutTable.getModel();
        int i = checkoutTable.getSelectedRow();
        tCost = tCost - ((Integer)model.getValueAt(i,4 ));
        double tax=0.025*tCost;
        SgstLabel.setText(Double.toString(tax));    
        CgstLabel.setText(Double.toString(tax));
        double fCost = tCost + 2*tax;
        TotalCost.setText(Double.toString(fCost));
        model.removeRow(checkoutTable.getSelectedRow());
    }//GEN-LAST:event_jButton2ActionPerformed
 
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        //
        int quantity;
        Boolean flag=false;
        int row=0,qty=0;
        String productID, Name="XYZ";
        //Double tCost;
        
        productID=ProIDtext.getText().toString();
        if(!pidCheck(productID) || productID.isEmpty())
            JOptionPane.showMessageDialog(this,"Product ID has to be an alphanumeric and cannot be null","Error",JOptionPane.INFORMATION_MESSAGE);
        else{
                //checking if pid is already present
           DefaultTableModel m = (DefaultTableModel) checkoutTable.getModel();
           for(int i=0;i<checkoutTable.getRowCount();i++)
           {
               if(m.getValueAt(i,0).equals(productID))
               {
                   flag = true;
                   row = i;
               }
           }
            if(flag)
            {
                //If ProductID exists increase qty                
                quantity=(Integer)QuantText.getValue();
                qty = (Integer)m.getValueAt(row, 3);
                qty += quantity;
                m.setValueAt(qty, row, 3);
                ProCost=BasePr*qty;
                m.setValueAt(ProCost, row, 4);
                tCost = (double)ProCost;
                double tax=0.025*tCost;
                SgstLabel.setText(Double.toString(tax));    
                CgstLabel.setText(Double.toString(tax));
                double fCost = tCost + 2*tax;
                TotalCost.setText(Double.toString(fCost));
                QuantText.setValue(1);                
            }
            else{
                quantity=(Integer)QuantText.getValue();
        
                //Code for getting product values goes here
        
                ProCost=BasePr*quantity;
                //Add Row with the above obtained product details:
        
                DefaultTableModel model = (DefaultTableModel)checkoutTable.getModel();
        
                model.addRow(new Object[]{productID,Name,BasePr,quantity,ProCost});
        
<<<<<<< HEAD
        tCost = tCost+ProCost;
        double tax=0.025*tCost;
        SgstLabel.setText(Double.toString(tax));    
        CgstLabel.setText(Double.toString(tax));
        double fCost = tCost + 2*tax;
        TotalCost.setText(Double.toString(fCost));
=======
                tCost = tCost+ProCost;
                double tax=0.025*tCost;
                SgstLabel.setText(Double.toString(tax));    
                CgstLabel.setText(Double.toString(tax));
                double fCost = tCost + 2*tax;
                TotalCost.setText(Double.toString(fCost));
                QuantText.setValue(1);
>>>>>>> baea9c2fab422b31210864ca61c8b2a8ce7076b3
        }
    }
        ProIDtext.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ProIDtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProIDtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProIDtextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel m = (DefaultTableModel) checkoutTable.getModel();
        int qty;
        for(int i=0;i<checkoutTable.getRowCount();i++)
        {
            if(i==checkoutTable.getSelectedRow())
                qty = Integer.parseInt((String)m.getValueAt(i, 3));
            else
                qty = (Integer)m.getValueAt(i, 3);
            if(qty<1)
                qty = 1;
            System.out.println(qty);
            m.setValueAt(qty, i, 3);
            ProCost=BasePr*qty;
            System.out.println(ProCost);
            m.setValueAt(ProCost, i, 4);
        }
        tCost = 0.0;
        for(int i=0;i<checkoutTable.getRowCount();i++)
        {
            tCost += (Integer)m.getValueAt(i, 4);
            double tax=0.025*tCost;
            SgstLabel.setText(Double.toString(tax));    
            CgstLabel.setText(Double.toString(tax));
            double fCost = tCost + 2*tax;
            TotalCost.setText(Double.toString(fCost));
            QuantText.setValue(1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CgstLabel;
    private javax.swing.JTextField ProIDtext;
    private javax.swing.JSpinner QuantText;
    private javax.swing.JLabel SgstLabel;
    private javax.swing.JTextField TotalCost;
    private javax.swing.JMenuItem checkoutInv;
    private javax.swing.JMenuItem checkoutLogout;
    private javax.swing.JMenu checkoutMenu;
    private javax.swing.JMenuItem checkoutSales;
    private javax.swing.JTable checkoutTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
};
